### PR TITLE
Update 3.6.0

### PR DESCRIPTION
**Pull request by ocefpaf**
Testing...

```
Changes in 3.6.0
2016-10-25

- Important / Breaking Changes:
  - The PHP binding moved to its own repository:
  http://git.osgeo.org/gogs/geos/php-geos (#765)
- New things:
  - CAPI: GEOSGeom_{get,set}UserData (Rashad Kanavath)
  - CAPI: GEOSGeom_{set,get}Precision (#713)
  - CAPI: GEOSMinimumRotatedRectangle and GEOSMinimumWidth
    (#729, Nyall Dawson)
  - CAPI: GEOSSTRtree_nearest (#768, Dan Baston)
  - CAPI: GEOSMinimumClearance and GEOSMinimumClearanceLine
    (#776, Dan Baston)
- C++ API changes:
  - Automatic memory management for GeometryFactory objects
```

### CODE REVIEW

**Comment by gillins** [comment]
Seems ok on Windows for py35, except last line of `bld.bat` should be:

```
copy include\geos\geos.h %LIBRARY_INC%\geos.h || exit 1
```

Since they have seemed to have moved it. Py27 and Py35 seem to have bigger problems - look like they will need patching if we decide to go with this release - might be a bit 'new' for other software - not sure....

**Comment by ocefpaf** [comment]
> if we decide to go with this release

My goal is `3.5.1` for now, once that one works I will update the pinnings. I am only experimenting with 3.6.0 so we can test the rest of the stack. It seems that they made some breaking changes.

**Comment by gillins** [comment]
Not sure what is happening on OSX, but I'll send you a PR for the Windows errors. I used to get the same errors with Solaris Studio - not sure if that was written by the same people as Visual Studio :grimacing:

**Comment by ocefpaf** [comment]
> Not sure what is happening on OSX

I believe we [always skipped](https://github.com/conda-forge/geos-feedstock/commit/0e61ec90bb7216ce20617f79709f26b79a227389) `make check` on `OS X`. I just tested it here to see if it would pass. But it seems that we still have that failure.

**Comment by ocefpaf** [comment]
:tada: 

Merging this but I will not pin to `geos 3.6.0` yet.

Thanks @gillins for the packages!

**Pull request merged**
