### PR TITLE
patch for pkg-config on win

### LINKED ISSUE #74: Windows builds lack .pc (pkg-config) file
Other platforms ship with a pkg-config file (geos.pc), but not the Windows builds. This lack of symmetry propagates as platform-specific build code. It would be great if this could be resolved!

I.e., please ship with `%PREFIX%\Library\lib\pkgconfig\geos.pc`.

Example downstream issue: https://github.com/conda-forge/r-terra-feedstock/pull/96

### PR DESCRIPTION
**Pull request by mfansler**
Adds a patch to unconditionally generate a .pc file.

Resolves #74

## Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Comment by mfansler** [comment]
@conda-forge/geos Any ideas on what the **linux-64** failure is here? Complains about `ctest` not recognizing `--exclude-regex` as an argument. That doesn't make sense to me - it shows CMake v3.30.1 is installed and that works fine on **osx-64** and **win-64**.

```cpp
...
[100%] Built target test_geos_unit
CMake Error: Unknown argument: --exclude-regex
CMake Error: Run 'ctest --help' for all supported options.
```

Otherwise, the **win-64** does show it now installs the `geos.pc` file, which is the point of the PR.

---

**NB:** Feel free to adjust the PR - I have nothing else planned for it.

**Comment by xylar** [comment]
@mfansler, the issue isn't with the `--exclude-regex` flag but with it having no argument passed to it under linux.  Hopefully fixed now.

**Review by ocefpaf — APPROVED** [review]
Thanks you two for fixing this.

**Comment by xylar** [comment]
@gillins, is this okay with you?  Referring to https://github.com/conda-forge/geos-feedstock/issues/74#issuecomment-2244162449.
> Always slightly nervous linking MSVC code with gcc code BTW, never quite sure what will happen.

**Review by xylar — APPROVED** [review]

**Comment by xylar** [comment]
@gillins, my suggestion is that we proceed.  Presumably if there are issues, it's because of what folks are doing downstream and not something we're directly responsible for ;-)

**Comment by xylar** [comment]
Thanks for posting the issue and the fix, @mfansler!

**Pull request merged**
