### PR TITLE
Set CXXFLAGS before configure

### PR DESCRIPTION
**Pull request by dbaston**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@ocefpaf (or someone else of the maintainers) can you take a look at this?

**Comment by jorisvandenbossche** [comment]
@dbaston this doesn't seem to have solved it. 
I just created a fresh environment, ensuring it is now using build he1b5a44_1 instead of he1b5a44_0, and I still see the same slowdown in the example of https://github.com/Toblerity/Shapely/issues/847#issuecomment-593598339

**Comment by jorisvandenbossche** [comment]
Tested with 

```
conda create -n test0 ipython geos=3.8.0=he1b5a44_0 pygeos
```

and

```
conda create -n test1 ipython geos=3.8.0=he1b5a44_1 pygeos
```

and the example code:

```
import numpy as np
import pygeos

t = np.arange(1, 10000)
arr = pygeos.points(100000*np.sin(t), 100000*np.sin(4*t)) 
arr2 = pygeos.buffer(arr, radius=200, quadsegs=32) 
union = pygeos.union_all(arr2) 

%timeit pygeos.buffer(union, radius=1) 
```

In both cases this is giving around 3 seconds (while with a local build of GEOS master gives around 60ms)

**Comment by jorisvandenbossche** [comment]
I checked locally the GEOS 3.8.0 tag as well, and then I also get a slowdown. So it seems the "performance fix" was only commited after 3.8.0, and might be a candidate for backporting to 3.8.x (if not yet done)

**Comment by jorisvandenbossche** [comment]
The GEOS 3.8.x branch is also slow, so opened https://github.com/libgeos/geos/issues/293

**Comment by ocefpaf** [comment]
@jorisvandenbossche would patching our 3.8.0 build with https://github.com/libgeos/geos/commit/1bf16cdf5a4827b483a1f712e0597ccb243f58cb help? If so I can do that now and we can add a speed test to the feedstock.

**Comment by jorisvandenbossche** [comment]
I think the plan is to release a 3.8.1 shortly, so would rather try to get it backported on the GEOS side first

**Comment by ocefpaf** [comment]
OK. Ping me if you need anything on the conda-forge side.

**Comment by jorisvandenbossche** [comment]
@ocefpaf it will be fixed in 3.8.1

**Comment by ocefpaf** [comment]
Awesome! We'll check the ABI and re-pin/migrate as needed.

**Pull request merged**
