### PR TITLE
Update

### PR DESCRIPTION
**Pull request by ocefpaf**
@gillins I probably need help here on Windows. Not sure what patches are still relevante or not.

### CODE REVIEW

**Comment by gillins** [comment]
Hmm not sure either. Last time I checked it looked like the next version (3.5.1) wouldn't need any patches since it seemed to be OK in their svn. 
Unfortunately I'm travelling for the next 2-3 weeks but I can have a proper look when I get back.

**Comment by ocefpaf** [comment]
> Unfortunately I'm travelling for the next 2-3 weeks but I can have a proper look when I get back.

No problem. There is no rush. I will try to set a Windows machine up and make some tests.

Enjoy your travels!

**Comment by gillins** [comment]
Is there any urgent need to update `geos`? I had been hoping to wait for 3.5.1 which may be easier to deal with whenever it is released.

**Comment by ocefpaf** [comment]
> Is there any urgent need to update `geos`?

Nope. 

> I had been hoping to wait for 3.5.1 which may be easier to deal with whenever it is released.

Sure! Let's wait for it. I will leave this open in case we have the need for `3.5.0` we can skip Windows and merge it.

**Comment by ocefpaf** [comment]
```
Changes in 3.5.1
2015-10-25

- Bug fixes / improvements
- Fix CMake configuration to allow build from released sources package (#753)
- Fix memory leaks in single-sided buffers (#747), PlanarGraph and tests
- Fix GeometryEditor to correctly update factory of empty geometries (#749)
- Fix snapping of last segment of a closed linestring (#758)
- Fix memory exhaustion case in isvalid (#757)
- Fix Windows build with Visual Studio 2008 (#766)
- Fix incorrect return from prepared multipoint intersects (#764)
- Fix build against GCC 3.5.0+ (#784)
```

**Comment by gillins** [comment]
Well done on noticing the new release @ocefpaf !
Seems to be a problem with the `cmake`. I get the same thing on my VM. I think this is the same problem mentioned here - https://trac.osgeo.org/geos/ticket/753. That file is still missing, although we can download it from https://trac.osgeo.org/geos/browser/trunk/cmake/modules. 
Linux and OSX seem fine since they are using the `configure` system.

Should we just include this file with the recipe and copy it into the right place?

**Comment by ocefpaf** [comment]
> Should we just include this file with the recipe and copy it into the right place?

I will try that. It is the easiest path :smile:

**Comment by gillins** [comment]
Well they aren't making it easy to build on Windows.... I _think_ you are safe to add:

```
echo "#define GEOS_SVN_REVISION 4298" > geos_svn_revision.h
```

To `bld.bat`. See https://trac.osgeo.org/geos/ticket/556. Obviously we can't easily run the .sh and we didn't use subversion to get the source anyway.... 4298 seems the last revision on the 3.5 branch.

**Comment by ocefpaf** [comment]
> Well they aren't making it easy to build on Windows....

Maybe I should try the `svn` source instead of working around these kinks. I went for GitHub hoping it would be a canonical one but it is just a mirror. I had to rename the README to get the build going! :unamused: 

I will try that later today.

**Comment by ocefpaf** [comment]
Awesome! The `svn` source is a no-no on `OS X`.

**Comment by gillins** [comment]
OK turns out DOS doesn't strip the quotes. Sorry. Try:

```
echo #define GEOS_SVN_REVISION 4298 > geos_svn_revision.h
```

hopefully that is it....

**Comment by ocefpaf** [comment]
> hopefully that is it....

No problem. Just made that change... Fingers crossed.

**Comment by gillins** [comment]
Ok seems there is more patching required. I should be able to look into this next week.

**Comment by ocefpaf** [comment]
> I should be able to look into this next week.

There is no rush. We are pinned to `geos 3.4.*`, so the update in defaults won't affect us. Once we get this working we need to update the pining [here](https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/pin_the_slow_way.py#L340).

BTW feel free to close this or merge as-is and work the Windows part later. I will try to see if I can move it forward a little bit too bit without a Windows machine it is quite painful.

**Comment by gillins** [comment]
Merging as-is. Will work on Windows support as separate PR.

**Comment by ocefpaf** [comment]
Thanks @gillins!

**Pull request merged**
