### PR TITLE
updated v3.10.1, use https for download

### PR DESCRIPTION
**Pull request by mwtoews**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mwtoews** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@mwtoews, are you completely sure the resulting packages will be identical?  If not, we should bump the build number because we could end up with different hashes for the same build.

**Comment by xylar** [comment]
Oh, sorry, ignore my comment.  I somehow missed that this was a new version.

**Review by xylar — APPROVED** [review]
Looks good.

**Comment by mwtoews** [comment]
> Oh, sorry, ignore my comment. I somehow missed that this was a new version.

I thought I'd beat @regro-cf-autotick-bot to get two changes thru

**Review by gillins — APPROVED** [review]

**Pull request merged**
