### PR TITLE
Add xylar as a maintainer

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
We're running into issues downstream with not having an ARM OSX build of 3.9.0.  If you're willing to add me as a maintainer, I would make a 3.9.0 branch and then do the ARM OSX migration there.

Back story is that we're stuck on `libspatialite`, which doesn't seem to support `geos` 3.9.1 yet: https://github.com/conda-forge/libspatialite-feedstock/pull/64

**Comment by gillins** [comment]
@xylar we ran into trouble with geos 3.9.0 and ARM OSX: https://github.com/conda-forge/geos-feedstock/pull/50 - good luck!

**Comment by xylar** [comment]
@gillins, Thanks.  I hadn't seen that this was already attempted.  It seems like we might be stuck for awhile then.  geos 3.9.0 doesn't support ARM OSX but libspatialite doesn't yet support geos 3.9.1.

**Pull request merged**
